export const COUNTER_INCREMENT = 'INCREMENT';
export const COUNTER_DECREMENT = 'DECREMENT';
export const COUNTER_RESET = 'RESET';
export const COUNTER_MULTIPLY = 'MULTIPLY';
export const COUNTER_DIVIDE = 'DIVIDE';
export const COUNTER_INCREMENT_BY_FACTOR = 'INCREMENT_BY_FACTOR';
export const COUNTER_DECREMENT_BY_FACTOR = 'DECREMENT_BY_FACTOR';
